apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      strategy: canary
  template:
    metadata:
      labels:
        app: demo
        strategy: canary
    spec:
      containers:
      - name: demo
        image: nginx:1.25

        ports:
        - containerPort: 80
